### ISSUE TITLE
La "quantité minimale" d'un article est remise à 0 quand on clique le bouton "Mettre à jour sans valider"

### ISSUE THREAD

**Issue by ykerb2** [grap/grap-odoo-custom-account#59]
La "quantité minimale" d'un article est remise à 0 quand on clique le bouton "Mettre à jour sans valider" pour  mettre à jour le prix de l'article.
![Mettre_a_jour_les_informations_fournisseur](https://github.com/grap/grap-odoo-custom-account/assets/102365433/9a38f2fe-824f-41da-8769-8b75cb35e388)

**Comment by carmenbianca** [comment]
Possibly fixed by https://github.com/OCA/account-invoicing/pull/1575 https://github.com/OCA/account-invoicing/pull/1574

**Comment by ykerb2** [comment]
A fix has been made somehow, somewhere (by Coop It Easy at least).
